# -*- coding: utf-8 -*-
"""Image Normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXXJrA3zs0Rn0mI16pXMv04IQ4EqGxxG
"""

# Load image

from google.colab import files

uploaded = files.upload()

pip install opencv-python numpy

import cv2
import numpy as np

image = cv2.imread("input.jpg")

# Convert to grayscale (8-bit)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Resize to 70% using Linear Interpolation

scale = 0.7

new_width = int(gray.shape[1] * scale)
new_height = int(gray.shape[0] * scale)

resized = cv2.resize(
    gray,
    (new_width, new_height),
    interpolation=cv2.INTER_LINEAR
)

restored = cv2.resize(
    resized,
    (gray.shape[1], gray.shape[0]),
    interpolation=cv2.INTER_LINEAR
)

cv2.imwrite("gray_image.png", gray)
cv2.imwrite("resized_07.png", resized)
cv2.imwrite("restored.png", restored)

from google.colab import files

files.download("gray_image.png")
files.download("resized_07.png")
files.download("restored.png")

from google.colab.patches import cv2_imshow

cv2_imshow(gray)
cv2_imshow(resized)
cv2_imshow(restored)

# Convert images to float to avoid overflow
original = gray.astype(np.float32)
reconstructed = restored.astype(np.float32)

# Difference
difference = original - reconstructed

# Square the differences
squared_difference = difference ** 2

# Average of squared differences (MSE)
average_squared_difference = np.mean(squared_difference)

print("Average Squared Difference (MSE):", average_squared_difference)